In [1]:
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import train_test_split

iris = datasets.load_iris()
x = iris.data
y = iris.target

classes = ['Iris Setosa', 'Iris Versicolour', 'Iris Virginica']

x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [2]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.4)

model = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto', probability=True)
model.fit(x_train, y_train)

prediction = model.predict(x_test)
percentage = accuracy_score(y_test, prediction)
acc = accuracy_score(y_test, prediction, normalize=False)
prediction

array([1, 2, 0, 2, 1, 2, 0, 1, 2, 1, 2, 2, 1, 1, 1, 1, 0, 1, 1, 0, 2, 2,
       1, 1, 1, 1, 2, 0, 1, 0, 0, 0, 0, 0, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2,
       0, 1, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 2, 2])

In [12]:
failed = 30 - acc
result = [classes[x] for x in prediction]
print(''.join(result))
print('accuracy_score: {} failed: {} Percentage: {:2f}'.format(acc, failed, percentage))


Iris VersicolourIris VirginicaIris SetosaIris VirginicaIris VersicolourIris VirginicaIris SetosaIris VersicolourIris VirginicaIris VersicolourIris VirginicaIris VirginicaIris VersicolourIris VersicolourIris VersicolourIris VersicolourIris SetosaIris VersicolourIris VersicolourIris SetosaIris VirginicaIris VirginicaIris VersicolourIris VersicolourIris VersicolourIris VersicolourIris VirginicaIris SetosaIris VersicolourIris SetosaIris SetosaIris SetosaIris SetosaIris SetosaIris VersicolourIris VirginicaIris VersicolourIris VirginicaIris VirginicaIris SetosaIris VersicolourIris SetosaIris VersicolourIris VirginicaIris SetosaIris VersicolourIris VirginicaIris SetosaIris SetosaIris SetosaIris SetosaIris SetosaIris VirginicaIris SetosaIris SetosaIris VirginicaIris VirginicaIris VirginicaIris VirginicaIris Virginica
accuracy_score: 59 failed: -29 Percentage: 0.983333
